### ISSUE TITLE
Error installing nugrant 2.1.2 with vagrant 1.8.1

### ISSUE THREAD

**Issue by JonaDupIO** [maoueh/nugrant#30]
Hi everybody.

I'm trying a manual install of nugrant 2.1.2 on windows, with a ```vagrant plugin install nugrant-2.1.2.gem``` and I have this error:

```Installing the 'nugrant-2.1.2.gem' plugin. This can take a few minutes...
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/package.rb:522:in `rescue in verify': No such file or directory @ rb_sysopen - nugrant-2.1.2.gem (Gem::Package::FormatError)```

I tried with an older version of Vagrant (1.7.4) and it works.

I saw that Vagrant 1.7.4 run with Ruby 2.0.0 instead of Vagrant 1.8.1 who use Ruby 2.2.0
Is it possible that Ruby has broke the thing?

Thanks

**Comment by maoueh** [comment]
Quite possible. Thanks for the report, I will check this out over the weekend and ensure `Nugrant` works with `Vagrant 1.8+`.

Will keep you posted.

**Comment by maoueh** [comment]
Hi,

I just tested Nugrant `2.1.2` with Vagrant 1.8.1 and it installed successfully. I then re-read your post and realized you are doing a manual install. Should have caught this earlier.

From what I read, you are not doing it correctly. Either you do not really want a "manual" installation in such case you should drop the version and the `.gem` suffix: `vagrant plugin install nugrant` to get the latest (or for a specific version `vagrant plugin install nugrant -v 2.1.0`).

Or, you really want a manual installation in which case, you are not specifying the location to the `gem` file correctly. The error message is saying so: `No such file or directory @ rb_sysopen - nugrant-2.1.2.gem`

But you also say that it works when you tried with Vagrant 1.7.4. Is it possible you did not run the exact same command.

Here what I tried to reproduce below. Closing for now. Feel free to re-open if you still think it's a bug. In which case, please provide the exact same steps as below but with your own results so I can investigate further.

Best regards,
Matt

```
Matt@WORKSTATION ~
$ vagrant -v
Vagrant 1.8.1

Matt@WORKSTATION ~
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [i386-mingw32]

Matt@WORKSTATION ~
$ bundle -v
Bundler version 1.10.6

Matt@WORKSTATION ~
$ mkdir -p /tmp/nugrant-issue-30

Matt@WORKSTATION /tmp
$ cd /tmp/nugrant-issue-30

Matt@WORKSTATION /tmp/nugrant-issue-30
$ git clone https://github.com/maoueh/nugrant.git
Cloning into 'nugrant'...

Matt@WORKSTATION /tmp/nugrant-issue-30
$ cd nugrant/

Matt@WORKSTATION /tmp/nugrant-issue-30/nugrant (master)
$ git checkout -b nugrant-2.1.2 v2.1.2
Switched to a new branch 'nugrant-2.1.2'

Matt@WORKSTATION /tmp/nugrant-issue-30/nugrant (nugrant-2.1.2)
$ bundle install
[Redacted]
Use `bundle show [gemname]` to see where a bundled gem is installed.

Matt@WORKSTATION /tmp/nugrant-issue-30/nugrant (nugrant-2.1.2)
$ rake build
nugrant 2.1.2 built to pkg/nugrant-2.1.2.gem.

Matt@WORKSTATION /tmp/nugrant-issue-30/nugrant (nugrant-2.1.2)
$ vagrant plugin install pkg/nugrant-2.1.2.gem
Installing the 'pkg/nugrant-2.1.2.gem' plugin. This can take a few minutes...
Installed the plugin 'nugrant (2.1.2)'!
```
