### ISSUE TITLE
 nugrant error:parameter machine was not found

### ISSUE THREAD

**Issue by Jyotiranjan150891** [maoueh/nugrant#35]
hi ,

i have tried to run vagrant up --provision.

I have all the setup in place.but i am getting above error but when checked the parameter machine it is there.

not sure how to resolve this issue.

please guide.

Thanks,
Jyotiranjan

**Comment by maoueh** [comment]
Sorry for the late reply, for an unknown reason, I don't get email notifications for my own repository!

To help you further, you will need to paste here your `Vagrantfile` and the actual full output text of the command.
