### ISSUE TITLE
Greetings bro

### ISSUE THREAD

**Issue by greenvalor13fox** [maoueh/nugrant#36]
I was hoping to pick your brain about this eos flare block and also if having # of confirmations are the ways to show that it has not been compromised by the powers of a outside influence to change the outcome of a seed or eos block hash in their favor because I find it odd not having any confirmation and as you stated 3 years ago.  this signature u referenced is back in the mix. SIG_K1_KYTPtoPd3Gx8LCR9rdCd6p3wGERwSuJtmw1LWDSSWfhxM7bWqy7mCTz8pBMtpYAbsPt7wYJFL6ax2HfHXqdXmm8rfDFdux

(If this link below is legit or not)
https://eosflare.io/block/320152732 

 Could i get up your opinion in this matter please as I am trying to figure out if they have been adding more code inside or what is it about manipulating the outcome . I would greatly appreciate if i can pick your brain about this and others that are legit and the ones that maybe fake or cloned. Thank you so much for your time. my telegram is 

Edward
 my telegram is telegram @foxy13fox

**Comment by maoueh** [comment]
It's quite bizarre that you contact me for an EOS/Antelope question on a repository that is totally unrelated to this world.

I'm not sure why should I be some kind of reference for `I was hoping to pick your brain about this eos flare block and also if having # of confirmations are the ways to show that it has not been compromised`. Not that I do not know the EOS stack very well, but there is probably better person them me for dealing with that.

If the block has been confirmed by at least 15/21 producers, then the block is deemed valid. If they 15 procuders are controlled by a small group of entity, they could do whatever they want and tweak the chain at their convenience. 

> because I find it odd not having any confirmation and as you stated 3 years ago

The block from the previous scheduled producer is also reporting 0 as confirmed and some of the current produced head block also like https://eos.eosq.eosnation.io/block/13179f5135cf950193584351fd864738dc30f822155b7054dd99c42b004afdb7 or https://eos.eosq.eosnation.io/block/13179fa85291111150570b7ea840993b7a5d233ef0f589818580cd9913963cd0

I personally don't think it's collusion. I would favor more an hypothesis like poor network condition(s), network health, a bug in the chain or another problem like that before collusion. But indeed, the network does not seems strong but it's still functioning.

You better ask people that are stil actively working with the chain like the guys at EOS Nation/Pinax.

**Comment by greenvalor13fox** [comment]
Thank you for your help and this helps alot. Have a great rest of your day!
